<a href="https://colab.research.google.com/github/kashish-vaish/jupyternotebooks/blob/main/GoogleMLCrashCourse/IntroToNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#Creating 1-D arrays
one_dim_arry = np.array([1,2,3,4,5])
print(one_dim_arry)

[1 2 3 4 5]


In [4]:
#Creating 2-D arrays
two_dim_arry = np.array([[1,1],[2,3],[6,9]])
print(two_dim_arry)

[[1 1]
 [2 3]
 [6 9]]


In [6]:
#Populating Zero array
zero_one_dim_array = np.zeros(5)
print(zero_one_dim_array)

zero_two_dim_array = np.zeros((5,5))
print(zero_two_dim_array)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
#Printing ones array
ones_one_dim_array = np.ones(5)
print(ones_one_dim_array)

ones_two_dim_array = np.ones((5,5))
print(ones_two_dim_array)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
#Generate a sequence, it includes lower bound but not upper bound
seq_arr = np.arange(5,12)
print(seq_arr)

[ 5  6  7  8  9 10 11]


In [17]:
#1-D array containing Random integers between 50 and 100
rand_arry = np.random.randint(50,101,size=(6,))
print(rand_arry)

#2-D array containing Random integers between 50 and 100
rand_arry = np.random.randint(50,101,size=(6,2))
print(rand_arry)

[73 74 71 95 58 80]
[[63 91]
 [70 60]
 [63 51]
 [68 77]
 [69 94]
 [62 55]]


In [19]:
#1-d array containing random floats between 0 and 1
rand_float = np.random.random((6,))
print(rand_float)

#2-d array containing random floats between 0 and 1
rand_float = np.random.random((6,2))
print(rand_float)

[0.52144377 0.73521008 0.98616988 0.85269871 0.41297831 0.48479223]
[[0.41616192 0.63531723]
 [0.16378777 0.77584662]
 [0.67001233 0.13865899]
 [0.46359133 0.85704629]
 [0.64134857 0.15161576]
 [0.45077606 0.34688514]]


In [23]:
#Mathematical operations
rand_float = np.random.random((6,2))
print(rand_float)
rand_float = rand_float +2.0
print(rand_float)

rand_float = np.random.random((6,2))
print(rand_float)
rand_float = rand_float * 3
print(rand_float)

[[0.17854161 0.28452064]
 [0.91305831 0.09220308]
 [0.60744609 0.70314106]
 [0.26930666 0.53622245]
 [0.50867326 0.16646264]
 [0.77884252 0.29602937]]
[[2.17854161 2.28452064]
 [2.91305831 2.09220308]
 [2.60744609 2.70314106]
 [2.26930666 2.53622245]
 [2.50867326 2.16646264]
 [2.77884252 2.29602937]]
[[0.98683063 0.18028531]
 [0.47237625 0.40080637]
 [0.93671982 0.27698796]
 [0.40343387 0.3738858 ]
 [0.44100968 0.97328597]
 [0.67495304 0.0688897 ]]
[[2.9604919  0.54085592]
 [1.41712874 1.20241911]
 [2.81015947 0.83096388]
 [1.2103016  1.12165739]
 [1.32302903 2.91985792]
 [2.02485911 0.20666909]]


Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.
Assign 15 values to a NumPy array named label such that:
label = (3)(feature) + 4

In [25]:
#Create a Linear Dataset

#creating a feature array

features = np.arange(6,21)
print(features)
label = ( features *3 )+4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [30]:
#Adding noise
noise = np.random.random(label.size)
noise = (noise*4)-2
print(noise)
print(label)
label =label +noise
print(label)

[-1.62177809 -0.19605117  1.8316259   1.1725559  -0.69086798  0.56170119
  0.31431571  0.42315818 -1.09149688 -0.20712457  1.35163489 -0.36865789
 -0.97566749  0.54887706  1.26351741]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]
[20.37822191 24.80394883 29.8316259  32.1725559  33.30913202 37.56170119
 40.31431571 43.42315818 44.90850312 48.79287543 53.35163489 54.63134211
 57.02433251 61.54887706 65.26351741]
