<a href="https://colab.research.google.com/github/kashish-vaish/jupyternotebooks/blob/main/GoogleMLCrashCourse/IntroToNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#Creating 1-D arrays
one_dim_arry = np.array([1,2,3,4,5])
print(one_dim_arry)

[1 2 3 4 5]


In [4]:
#Creating 2-D arrays
two_dim_arry = np.array([[1,1],[2,3],[6,9]])
print(two_dim_arry)

[[1 1]
 [2 3]
 [6 9]]


In [6]:
#Populating Zero array
zero_one_dim_array = np.zeros(5)
print(zero_one_dim_array)

zero_two_dim_array = np.zeros((5,5))
print(zero_two_dim_array)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
#Printing ones array
ones_one_dim_array = np.ones(5)
print(ones_one_dim_array)

ones_two_dim_array = np.ones((5,5))
print(ones_two_dim_array)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
#Generate a sequence, it includes lower bound but not upper bound
seq_arr = np.arange(5,12)
print(seq_arr)

[ 5  6  7  8  9 10 11]
